### ISSUE TITLE
Create a Basic Environment 

### ISSUE THREAD

**Issue by ryanjackson22** [CSI-280-Fish-Game/Fish-Game#30]
Create a visual environment that we can place the sprites onto.

**Comment by katiepo456** [comment]
The Collision attempt pull request implemented a temporary background image. I added a TextureRect child node to the main scene and attached a default fishing level background image. This is a placeholder until we have the original art to import. I found out that the hierarchy of children nodes orders the layering as it appears, so the background node needs to be highest in order to be sent to the back.
